[package]
name = "dustdb"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
bincode = "1"
parking_lot = "0.12"
uuid = { version = "1", features = ["v4"] }

